### ISSUE TITLE
Get the video shader examples keeping a proper ratio.

### ISSUE THREAD

**Issue by AlexisTM** [aferriss/p5jsShaderExamples#1] opened 2019-04-07 15:26 UTC
**Problem**

When resizing the window to a ratio different than the camera ratio, the image is distorted on every example.

**Expected**

The image is centered and resized keeping the image ratio of the camera.

**Comment by phantom7knight** [comment] 2019-08-25 04:20
Hey I don't know if this is a problem with me or not but I can't view any of the shaders. Let's say if I try to open this`https://aferriss.github.io/p5jsShaderExamples/4_image-effects/4-6_pixelate/` I don't see anything.

**Comment by aferriss** [comment] 2019-08-26 17:08
@phantom7knight Hmm, seems to be working for me. What browser are you using? You'll need to allow camera access in order to run the sketch

**Comment by aferriss** [comment] 2019-08-26 17:12
@AlexisTM Yea, this is partly by design. I'd be open to PR's to take this into account but but for now they will probably stay the way they are. It should be an easy change to make. Youll just need to update any uniforms pertaining to window size when on window resize events. You'll have to update graphics layer sizes as well.

Another approach that would work but might result in some weird artifacting is to set the size of the sketch canvas via css. 

Here's a sketch with the gist of the first approach...https://editor.p5js.org/aferriss/sketches/rJAwGb_AW

I'm going to close this issue for now but feel free to reopen if you have further questions

**Closed as completed by aferriss** 2019-08-26 17:12 UTC
